### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vhundef** [vhundef/spo_Compiler_cpp#15]
Lexer

- [x] Считывание файла
- [x] Разбивка на токены

Parser
- [x] Создание AST

Semantic Analyzer
- [x] Проверка правильности типов
- [x] Проверка объявления функций и переменных

Translator

- [ ] ??
